name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RPI_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add Pi to known_hosts
        run: ssh-keyscan -H ${{ secrets.RPI_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script on Raspberry Pi
        run: ssh ${{ secrets.RPI_USER }}@${{ secrets.RPI_HOST }} "~/deploy-moneysort.sh"
